// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARb9bWA9ddzYouF0G3FXg2qr0-t0yeK9E',
    appId: '1:172191907223:web:b53283ffd2d7abb72498d2',
    messagingSenderId: '172191907223',
    projectId: 'rush10-228be',
    authDomain: 'rush10-228be.firebaseapp.com',
    storageBucket: 'rush10-228be.firebasestorage.app',
    measurementId: 'G-EMM0VWWC2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIEN7JuAKbAf6s6HQ_LEBh_4_dnWkLrOg',
    appId: '1:172191907223:android:20427ce6b32e715c2498d2',
    messagingSenderId: '172191907223',
    projectId: 'rush10-228be',
    storageBucket: 'rush10-228be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWyS5yBXOKjBO6qwhp9AgayHH__F5EzCw',
    appId: '1:172191907223:ios:5eacfaab742a344d2498d2',
    messagingSenderId: '172191907223',
    projectId: 'rush10-228be',
    storageBucket: 'rush10-228be.firebasestorage.app',
    iosBundleId: 'com.example.rush10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWyS5yBXOKjBO6qwhp9AgayHH__F5EzCw',
    appId: '1:172191907223:ios:5eacfaab742a344d2498d2',
    messagingSenderId: '172191907223',
    projectId: 'rush10-228be',
    storageBucket: 'rush10-228be.firebasestorage.app',
    iosBundleId: 'com.example.rush10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARb9bWA9ddzYouF0G3FXg2qr0-t0yeK9E',
    appId: '1:172191907223:web:d12fb4d4d8132db32498d2',
    messagingSenderId: '172191907223',
    projectId: 'rush10-228be',
    authDomain: 'rush10-228be.firebaseapp.com',
    storageBucket: 'rush10-228be.firebasestorage.app',
    measurementId: 'G-D4T2J07Y4N',
  );
}
